# theme: jekyll-theme-hacker
remote_theme: andrewbanchich/forty-jekyll-theme

title: 25AM
subtitle: Nowhere in the world
email: youremailaddress@gmail.com
description: A personal page.
#baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
#url: # the base hostname & protocol for your site
author: X.Y.
#street_address: 1234 Somewhere Road
#city: Nashville
#state: TN
#zip_code: 55555
#country: United States of America
#phone: (716) 555-5555

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
github_url: https://github.com/XYUnknown
instagram_url: https://instagram.com

# build settings
markdown: kramdown

sass:
  style: compressed
